services:
  gecholog:
    build:
      context: .
      dockerfile: gecholog.Dockerfile
    container_name: gecholog
    ports:
      - 5380:5380
      - 4222:4222
      - 8080:8080
    environment:
      - NATS_TOKEN=${NATS_TOKEN}
      - GUI_SECRET=${GUI_SECRET}
      - AISERVICE_API_BASE=${AISERVICE_API_BASE}
    networks:
      - gecholog-network
    healthcheck:
      interval: 1s
      retries: 10

  charachtercount:
    depends_on:
      gecholog:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: charactercount
    environment:
      - NATS_TOKEN=${NATS_TOKEN}
      - GECHOLOG_HOST=gecholog
    networks:
      - gecholog-network

networks:
  gecholog-network:
    driver: bridge
